import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts";

import Card from "../components/Card";
import Button from "../components/Button";

function Dashboard() {

  const stats = [
    {
      title: "Profile Score",
      value: "85%",
      description: "AI analyzed",
    },
    {
      title: "Gigs Optimized",
      value: "12",
      description: "This month",
    },
    {
      title: "Proposals Created",
      value: "28",
      description: "Generated by AI",
    },
  ];


  const chartData = [
    {
      day: "Mon",
      score: 60,
    },
    {
      day: "Tue",
      score: 68,
    },
    {
      day: "Wed",
      score: 72,
    },
    {
      day: "Thu",
      score: 78,
    },
    {
      day: "Fri",
      score: 85,
    },
    {
      day: "Sat",
      score: 90,
    },
  ];


  const features = [
    {
      title: "Profile Analyzer",
      description:
        "Get AI suggestions to improve your freelancer profile.",
      route: "/dashboard/profile-analyzer",
    },
    {
      title: "Gig SEO Optimizer",
      description:
        "Improve ranking with AI-powered keyword optimization.",
      route: "/dashboard/gig-seo",
    },
    {
      title: "Proposal Generator",
      description:
        "Create winning proposals in seconds using AI.",
      route: "/dashboard/proposal-generator",
    },
  ];


  return (
    <div className="p-8 space-y-10">


      {/* Header */}

      <div>
        <h1 className="text-4xl font-bold text-gray-900">
          Welcome back, Freelancer 👋
        </h1>

        <p className="mt-3 text-gray-600 max-w-2xl">
          Manage your AI tools, optimize gigs, and improve
          your chances of winning freelance projects.
        </p>
      </div>



      {/* Stats */}

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">

        {stats.map((item)=>(
          <Card
            key={item.title}
            className="p-6 shadow-md"
          >

            <p className="text-gray-500">
              {item.title}
            </p>

            <h2 className="text-4xl font-bold text-primaryBlue mt-3">
              {item.value}
            </h2>

            <p className="text-sm text-gray-500 mt-2">
              {item.description}
            </p>

          </Card>
        ))}

      </div>



      {/* Graph */}

      <Card className="p-6 shadow-md">

        <h2 className="text-xl font-bold text-gray-800 mb-6">
          Profile Growth Score
        </h2>


        <ResponsiveContainer width="100%" height={300}>

          <LineChart data={chartData}>

            <CartesianGrid strokeDasharray="3 3"/>

            <XAxis dataKey="day"/>

            <YAxis/>

            <Tooltip/>

            <Line
              type="monotone"
              dataKey="score"
              stroke="#1A56DB"
              strokeWidth={3}
            />

          </LineChart>

        </ResponsiveContainer>

      </Card>




      {/* AI Tools */}

      <div>

        <h2 className="text-2xl font-bold mb-6">
          AI Freelancer Tools
        </h2>


        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">

          {features.map((feature)=>(

            <Card
              key={feature.title}
              className="p-6 shadow-lg hover:shadow-xl transition hover:-translate-y-1"
            >

              <h3 className="text-xl font-bold text-gray-800">
                {feature.title}
              </h3>


              <p className="mt-3 text-gray-600">
                {feature.description}
              </p>


              <Button className="mt-5">
                Launch Tool
              </Button>


            </Card>

          ))}

        </div>

      </div>




      {/* Activity */}

      <Card className="p-6 shadow-md">

        <h2 className="text-xl font-bold mb-4">
          Recent AI Activity
        </h2>


        <ul className="space-y-3 text-gray-600">

          <li>
            ✓ Profile analyzed successfully
          </li>

          <li>
            ✓ New SEO keywords generated
          </li>

          <li>
            ✓ Proposal created for Web Development gig
          </li>

        </ul>

      </Card>


    </div>
  );
}

export default Dashboard;