import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts";

import Card from "../components/Card";
import Button from "../components/Button";
import Modal from "../components/Modal";
import Skeleton from "../components/Skeleton";

function Dashboard() {
  const navigate = useNavigate();

  const [loading, setLoading] = useState(true);
  const [open, setOpen] = useState(false);
  const [selectedHistory, setSelectedHistory] = useState(null);

  useEffect(() => {
    const timer = setTimeout(() => {
      setLoading(false);
    }, 1500);

    return () => clearTimeout(timer);
  }, []);

  const stats = [
    {
      title: "Profile Score",
      value: "85%",
      description: "AI analyzed",
    },
    {
      title: "Total SEO",
      value: "12",
      description: "Optimized gigs",
    },
    {
      title: "Total Proposals",
      value: "28",
      description: "Generated by AI",
    },
  ];

  const chartData = [
    { day: "Mon", score: 60 },
    { day: "Tue", score: 68 },
    { day: "Wed", score: 72 },
    { day: "Thu", score: 78 },
    { day: "Fri", score: 85 },
    { day: "Sat", score: 90 },
  ];

  const features = [
    {
      title: "Profile Analyzer",
      description:
        "Get AI suggestions to improve your freelancer profile.",
      route: "/dashboard/profile-analyzer",
    },
    {
      title: "Gig SEO Optimizer",
      description:
        "Improve ranking with AI-powered keyword optimization.",
      route: "/dashboard/gig-seo",
    },
    {
      title: "Proposal Generator",
      description:
        "Create winning proposals in seconds using AI.",
      route: "/dashboard/proposal-generator",
    },
  ];

  const recentHistory = [
    {
      type: "Profile",
      text: "Profile analyzed successfully",
    },
    {
      type: "SEO",
      text: "Generated optimized SEO keywords",
    },
    {
      type: "Proposal",
      text: "Proposal created for Web Development job",
    },
  ];

  return (
    <div className="p-6 md:p-8 space-y-8">

      {/* Header */}

      <div>
        <h1 className="text-4xl font-bold text-gray-900">
          Welcome back, Freelancer 👋
        </h1>

        <p className="mt-3 text-gray-600 max-w-2xl">
          Manage your AI tools, optimize gigs, and improve your chances
          of winning freelance projects.
        </p>
      </div>

      {loading ? (
        <div className="space-y-6">

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <Skeleton className="h-32" />
            <Skeleton className="h-32" />
            <Skeleton className="h-32" />
          </div>

          <Skeleton className="h-80" />

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <Skeleton className="h-56" />
            <Skeleton className="h-56" />
            <Skeleton className="h-56" />
          </div>

        </div>
      ) : (
        <>

          {/* Usage Banner */}

          <Card className="border border-blue-200 p-5">

            <div className="flex flex-col md:flex-row justify-between items-center gap-4">

              <div>
                <h2 className="text-lg font-semibold text-gray-900">
                  Daily Usage
                </h2>

                <p className="text-gray-600">
                  3 of 5 free uses remaining today
                </p>
              </div>

              <Button>
                Upgrade to Pro
              </Button>

            </div>

          </Card>

          {/* Stats */}

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">

            {stats.map((item) => (

              <Card
                key={item.title}
                className="shadow-md hover:shadow-xl transition"
              >

                <p className="text-gray-500">
                  {item.title}
                </p>

                <h2 className="text-4xl font-bold text-primaryBlue mt-2">
                  {item.value}
                </h2>

                <p className="text-sm text-gray-500 mt-2">
                  {item.description}
                </p>

              </Card>

            ))}

          </div>

          {/* Growth Chart */}

          <Card className="shadow-md">

            <h2 className="text-xl font-bold text-gray-800 mb-6">
              Profile Growth Score
            </h2>

            <ResponsiveContainer
              width="100%"
              height={300}
            >

              <LineChart data={chartData}>

                <CartesianGrid strokeDasharray="3 3" />

                <XAxis dataKey="day" />

                <YAxis />

                <Tooltip />

                <Line
                  type="monotone"
                  dataKey="score"
                  stroke="#1A56DB"
                  strokeWidth={3}
                />

              </LineChart>

            </ResponsiveContainer>

          </Card>
                    {/* AI Tools */}

          <div>

            <div className="flex items-center justify-between mb-6">

              <h2 className="text-2xl font-bold text-gray-900">
                AI Freelancer Tools
              </h2>

              <p className="text-sm text-gray-500">
                Choose a tool to get started
              </p>

            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">

              {features.map((feature) => (

                <Card
                  key={feature.title}
                  className="shadow-lg hover:shadow-xl transition-all duration-300 hover:-translate-y-1"
                >

                  <h3 className="text-xl font-bold text-gray-900">
                    {feature.title}
                  </h3>

                  <p className="mt-3 text-gray-600">
                    {feature.description}
                  </p>

                  <Button
                    className="mt-6 w-full h-12"
                    onClick={() => navigate(feature.route)}
                  >
                    Launch Tool
                  </Button>

                </Card>

              ))}

            </div>

          </div>

          {/* Recent History */}

          <Card className="shadow-md">

            <div className="flex items-center justify-between mb-6">

              <h2 className="text-xl font-bold text-gray-900">
                Recent History
              </h2>

              <Button
                onClick={() => navigate("/dashboard/history")}
              >
                View All
              </Button>

            </div>

            <div className="space-y-4">

              {recentHistory.map((item, index) => (

                <div
                  key={index}
                  className="flex flex-col md:flex-row md:items-center md:justify-between border-b border-gray-200 pb-4"
                >

                  <div>

                    <span className="inline-block px-3 py-1 rounded-full bg-blue-100 text-blue-700 text-xs font-semibold mb-2">
                      {item.type}
                    </span>

                    <p className="text-gray-700">
                      {item.text}
                    </p>

                  </div>

                  <Button
                    onClick={() => {
                      setSelectedHistory(item);
                      setOpen(true);
                    }}
                  >
                    View
                  </Button>

                </div>

              ))}

            </div>

          </Card>

          {/* Modal */}

          <Modal
            isOpen={open}
            onClose={() => {
              setOpen(false);
              setSelectedHistory(null);
            }}
            title={selectedHistory?.type || "Recent Activity"}
          >

            <div className="space-y-4">

              <p className="text-gray-700">
                {selectedHistory?.text}
              </p>

              <Button
                onClick={() =>
                  navigator.clipboard.writeText(
                    selectedHistory?.text || ""
                  )
                }
              >
                Copy
              </Button>

            </div>

          </Modal>

        </>
      )}

    </div>
  );
}

export default Dashboard;